### PR TITLE
bug: fixed time change issue #50

### PR DESCRIPTION
**Pull request by namansharma3007**
## Pull Request Summary
- I have successfully resolved issue #50.
## Changes Made
- The dropdown now automatically updates when the minimum time aligns with the current time.
- Users are restricted from making bookings for the present time; bookings can only be made for future times.
- Please refer to the attached video for a complete overview of the changes. The system time is displayed in the bottom right corner for comparison. Thank you!

https://github.com/user-attachments/assets/81eacbcd-fb86-40f3-9312-2399ff9ce9c5

### CODE REVIEW

**Comment by Propo41** [comment]
@namansharma3007 please reflect on the PR feedback

**Comment by namansharma3007** [comment]
@Propo41 I have successfully attached the Proof of work. Please, check.

**Comment by Propo41** [comment]
> @Propo41 I have successfully attached the Proof of work. Please, check.

I understand that it works, but it's too much code change and can be done more easily.

**Comment by namansharma3007** [comment]
> > @Propo41 I have successfully attached the Proof of work. Please, check.
> 
> I understand that it works, but it's too much code change and can be done more easily.

I understand your point. But if you notice carefully. Its only addition of useEffect hook and setTimeInterval. This was the easiest way you can track latest changes in state of time.

**Comment by Propo41** [comment]
> > > @Propo41 I have successfully attached the Proof of work. Please, check.
> > 
> > 
> > I understand that it works, but it's too much code change and can be done more easily.
> 
> I understand your point. But if you notice carefully. Its only addition of useEffect hook and setTimeInterval. This was the easiest way you can track latest changes in state of time.

I have went through the code, and have decided not to go for this approach. The preferred approach is as follows: 

> When user clicks the book button, compare the `startTime` with the current time (Date.now()). If it does not match, then show an alert toast and re-populate the dropdown items again. 

** Make sure to pull latest code from develop.

**Pull request closed without merging**
